language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-11
#travis ci terminates unexpectedly, when running some tests, we will skip those for now 
## TODO: refactor specific tests which are excluded into its own file.
script: mvn clean install -Dmaven.javadoc.skip=true -Daws-android-sdk-kinesis.test.excludes=**/FileRecordStoreTest.java
