language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-11
env:
  global:
    - MAVEN_OPTS="-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m"
#travis ci terminates unexpectedly, when running some tests, we will skip those for now 
## TODO: refactor specific tests which are excluded into its own file.
script: mvn clean install -Dmaven.javadoc.skip=true
